/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vulnapp_modsecurity_wrappers_ModSecurityWrapper */

#ifndef _Included_vulnapp_modsecurity_wrappers_ModSecurityWrapper
#define _Included_vulnapp_modsecurity_wrappers_ModSecurityWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vulnapp_modsecurity_wrappers_ModSecurityWrapper
 * Method:    wrapFilterRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_vulnapp_modsecurity_wrappers_ModSecurityWrapper_wrapFilterRequest
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
